{% set name = "osqp-eigen" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d47726747d61c1d251a6ef7741fbfb0374fbe9e1f263f1cb610299166b774926

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    - cmake
  host:
    - libosqp
    - eigen
  run:
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/OsqpEigen/OsqpEigen.h  # [not win]
    - test -f ${PREFIX}/lib/cmake/OsqpEigen/OsqpEigenConfig.cmake  # [not win]
    - test -f ${PREFIX}/lib/libOsqpEigen.so  # [linux]
    - test -f ${PREFIX}/lib/libOsqpEigen.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\include\\OsqpEigen\\OsqpEigen.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\OsqpEigen.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\OsqpEigen.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\OsqpEigen\\OsqpEigenConfig.cmake exit 1  # [win]

about:
  home: https://github.com/robotology/osqp-eigen
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Simple C++ wrapper for osqp library.

extra:
  recipe-maintainers:
    - GiulioRomualdi
    - traversaro
